"""change_string_columns_to_text

Revision ID: 7c4c8297b15e
Revises: 9d6ddc8593eb
Create Date: 2025-06-28 20:12:32.033497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4c8297b15e'
down_revision = '9d6ddc8593eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('permissions', 'resource',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('permissions', 'action',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=False,
               schema='auth')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions', schema='auth')
    op.create_index(op.f('ix_auth_permissions_name'), 'permissions', ['name'], unique=True, schema='auth')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False,
               schema='auth')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles', schema='auth')
    op.create_index(op.f('ix_auth_roles_tenant_id'), 'roles', ['tenant_id'], unique=False, schema='auth')
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('tenants', 'domain',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False,
               schema='auth')
    op.drop_index(op.f('ix_tenants_domain'), table_name='tenants', schema='auth')
    op.create_index(op.f('ix_auth_tenants_domain'), 'tenants', ['domain'], unique=True, schema='auth')
    op.drop_index(op.f('ix_user_tenant_roles_role_id'), table_name='user_tenant_roles', schema='auth')
    op.drop_index(op.f('ix_user_tenant_roles_tenant_id'), table_name='user_tenant_roles', schema='auth')
    op.drop_index(op.f('ix_user_tenant_roles_user_id'), table_name='user_tenant_roles', schema='auth')
    op.create_index(op.f('ix_auth_user_tenant_roles_role_id'), 'user_tenant_roles', ['role_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_tenant_roles_tenant_id'), 'user_tenant_roles', ['tenant_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_tenant_roles_user_id'), 'user_tenant_roles', ['user_id'], unique=False, schema='auth')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('users', 'reset_password_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True,
               schema='auth')
    op.drop_index(op.f('ix_users_email'), table_name='users', schema='auth')
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.drop_column('users', 'verification_token', schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.alter_column('users', 'reset_password_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='auth')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               schema='auth')
    op.alter_column('users', 'last_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='auth')
    op.alter_column('users', 'first_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='auth')
    op.alter_column('users', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               schema='auth')
    op.drop_index(op.f('ix_auth_user_tenant_roles_user_id'), table_name='user_tenant_roles', schema='auth')
    op.drop_index(op.f('ix_auth_user_tenant_roles_tenant_id'), table_name='user_tenant_roles', schema='auth')
    op.drop_index(op.f('ix_auth_user_tenant_roles_role_id'), table_name='user_tenant_roles', schema='auth')
    op.create_index(op.f('ix_user_tenant_roles_user_id'), 'user_tenant_roles', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_user_tenant_roles_tenant_id'), 'user_tenant_roles', ['tenant_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_user_tenant_roles_role_id'), 'user_tenant_roles', ['role_id'], unique=False, schema='auth')
    op.drop_index(op.f('ix_auth_tenants_domain'), table_name='tenants', schema='auth')
    op.create_index(op.f('ix_tenants_domain'), 'tenants', ['domain'], unique=True, schema='auth')
    op.alter_column('tenants', 'domain',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               schema='auth')
    op.alter_column('tenants', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               schema='auth')
    op.drop_index(op.f('ix_auth_roles_tenant_id'), table_name='roles', schema='auth')
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False, schema='auth')
    op.alter_column('roles', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='auth')
    op.drop_index(op.f('ix_auth_permissions_name'), table_name='permissions', schema='auth')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True, schema='auth')
    op.alter_column('permissions', 'action',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               schema='auth')
    op.alter_column('permissions', 'resource',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='auth')
    op.alter_column('permissions', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='auth')
    # ### end Alembic commands ###
