name: Database Migrations

on:
  workflow_run:
    workflows: ["Backend Tests"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  migrations:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Run migrations for auth service
      run: |
        cd backend/auth-service
        chmod +x ./run_migrations.sh
        # Pass the database URL directly to the script
        ./run_migrations.sh
      shell: bash
      env:
        # Use DATABASE_URL directly as that's what the script expects
        DATABASE_URL: ${{ secrets.AUTH_DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        PYTHONUNBUFFERED: 1

    - name: Run migrations for dentist service
      run: |
        cd backend/dentist-service
        chmod +x ./run_migrations.sh
        # Pass the database URL directly to the script
        ./run_migrations.sh
      shell: bash
      env:
        # Use DATABASE_URL directly as that's what the script expects
        DATABASE_URL: ${{ secrets.DENTIST_DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        PYTHONUNBUFFERED: 1
